version: '3.7'

services:
    php:
        build:
            context: ./
        depends_on:
            - db
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${EXTERNAL_HTTP_PORT-80}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: mariadb:10.4
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
          - db:/var/lib/mysql

volumes:
    db: