<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["contacts", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit contacts</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="contacts/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhoneNumber" class="col-sm-2 control-label">Phone Of Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", "id" => "fieldPhoneNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountryCode" class="col-sm-2 control-label">Country Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["country_code", "size" => 30, "class" => "form-control", "id" => "fieldCountryCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTimezone" class="col-sm-2 control-label">Timezone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["timezone", "size" => 30, "class" => "form-control", "id" => "fieldTimezone"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldInsertedOn" class="col-sm-2 control-label">Inserted Of On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["inserted_on", "size" => 30, "class" => "form-control", "id" => "fieldInsertedOn"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedOn" class="col-sm-2 control-label">Updated Of On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updated_on", "size" => 30, "class" => "form-control", "id" => "fieldUpdatedOn"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
