<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["contacts/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["contacts/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>First Of Name</th>
            <th>Last Of Name</th>
            <th>Phone Of Number</th>
            <th>Country Of Code</th>
            <th>Timezone</th>
            <th>Inserted Of On</th>
            <th>Updated Of On</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $contact): ?>
            <tr>
                <td><?php echo $contact->id ?></td>
            <td><?php echo $contact->first_name ?></td>
            <td><?php echo $contact->last_name ?></td>
            <td><?php echo $contact->phone_number ?></td>
            <td><?php echo $contact->country_code ?></td>
            <td><?php echo $contact->timezone ?></td>
            <td><?php echo $contact->inserted_on ?></td>
            <td><?php echo $contact->updated_on ?></td>

                <td><?php echo $this->tag->linkTo(["contacts/edit/" . $contact->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["contacts/delete/" . $contact->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["contacts/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
